
POST http://localhost:8080/users/create
Content-Type: application/json

{
    "firstName": "Megan",
    "lastName": "Fox",
    "email": "megan.fox@gmail.com",
    "username": "mega_fox",
    "password": "99999999"
}

###

GET http://localhost:8080/users/4d650993-5646-4246-a42b-a39cfdef450b


###

GET http://localhost:8080/users


###